### ISSUE TITLE
UDS 2024 Punchlist

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/unifyingdatascience#46]
- [ ] Add chatGPT to syllabus #45 
- [ ] Write intro to causal inference on ds4humans
- [ ] Move exploratory questions exercise up in the schedule, make it mastery learning. #44 
- [ ] Update midterm: it make all multiple choice (#43) move answers to a second sheet of paper (#42)
- [ ] Check on difference indifference exercise #39
- [ ] Update final assignment to only have policy/stakeholder version
- [ ] Think about race/gender examples
